
version: '3.8'

services:
  grpc-server:
    build: .
    ports:
      - "50051:50051"
    volumes:
      - ./models:/opt/models
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
